language: python

matrix:
  include:
    - python: 3.9
      env: TOXENV=py39-django32
    - python: 3.10
      env: TOXENV=py310-django32
    - python: 3.11
      env: TOXENV=py311-django32
    - python: 3.9
      env: TOXENV=py39-django42
    - python: 3.10
      env: TOXENV=py310-django42
    - python: 3.11
      env: TOXENV=py311-django42
    - env: TOXENV=flake8

install:
  - pip install tox

script:
  - tox -v
